services:
  check_bot_inserts:
    build:
      context: ./check_bot_inserts
    links:
    - db
    ports:
    - 6011
    restart: always
    volumes:
    - /home/clara/dump/dockers/face_recognition/check_bot_inserts:/app
    - /home/clara/dump/dockers/face_recognition/volumes:/volumes

  classifier_creator:
    build:
      context: ./classifier_creator
    links:
    - db
    ports:
    - 6010
    restart: always
    volumes:
    - /home/clara/dump/dockers/face_recognition/classifier_creator:/app
    - /home/clara/dump/dockers/face_recognition/volumes:/volumes

  classify:
    build:
      context: ./classify
    links:
    - db
    ports:
    - 6008
    restart: always
    volumes:
    - /home/clara/dump/dockers/face_recognition/classify:/app
    - /home/clara/dump/dockers/face_recognition/volumes:/volumes

  db:
    build:
      context: ./db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
    - 5432:5432
    volumes:
    - /home/clara/dump/dockers/face_recognition/volumes/postgresql/9.5/main:/var/lib/postgresql/data

  detector:
    build:
      context: ./detector
    devices:
    - /dev/nvidia0
    - /dev/nvidiactl
    - /dev/nvidia-uvm
    - /dev/nvidia-uvm-tools
    ports:
    - 6006
    restart: always
    volumes:
    - /home/clara/dump/dockers/face_recognition/detector:/app
    - /home/clara/dump/dockers/face_recognition/volumes:/volumes
    - nvidia_driver_390.87:/usr/local/nvidia:ro

  identification:
    build:
      context: ./identification
    devices:
    - /dev/nvidia0
    - /dev/nvidiactl
    - /dev/nvidia-uvm
    - /dev/nvidia-uvm-tools
    ports:
    - 6007
    restart: always
    volumes:
    - /home/clara/dump/dockers/face_recognition/identification:/app
    - /home/clara/dump/dockers/face_recognition/volumes:/volumes
    - nvidia_driver_390.87:/usr/local/nvidia:ro

  photo_push:
    build:
      context: ./photo_push
    ports:
    - 6009
    restart: always
    volumes:
    - /home/clara/dump/dockers/face_recognition/photo_push:/app
    - /home/clara/dump/dockers/face_recognition/volumes:/volumes

version: '2'
volumes:
    nvidia_driver_390.87:
        external: true
